ARG ZED_ROS_BASE_IMAGE=stereolabs/zed:5.3-tools-devel-cuda12.8-ubuntu24.04
FROM ${ZED_ROS_BASE_IMAGE}

ARG ROS_DISTRO=jazzy
ENV DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=${ROS_DISTRO} \
    PYTHONUNBUFFERED=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1

RUN apt-get update && apt-get install -y --no-install-recommends \
      bash ca-certificates curl gnupg lsb-release software-properties-common locales \
      git jq less nano build-essential cmake python3-pip python3-venv python3-numpy python3-opencv \
      usbutils v4l-utils pciutils mesa-utils x11-apps \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
      -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
      > /etc/apt/sources.list.d/ros2.list \
    && apt-get update && apt-get install -y --no-install-recommends \
      ros-${ROS_DISTRO}-ros-base \
      ros-${ROS_DISTRO}-rviz2 \
      ros-${ROS_DISTRO}-image-transport \
      ros-${ROS_DISTRO}-image-transport-plugins \
      ros-${ROS_DISTRO}-compressed-image-transport \
      ros-${ROS_DISTRO}-compressed-depth-image-transport \
      ros-${ROS_DISTRO}-tf2-ros \
      ros-${ROS_DISTRO}-rosbag2 \
      ros-${ROS_DISTRO}-rosbag2-storage-mcap \
      python3-colcon-common-extensions python3-rosdep python3-vcstool \
    && rosdep init || true \
    && rosdep update \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/zed_ros2_ws/src \
    && cd /opt/zed_ros2_ws/src \
    && git clone --depth=1 https://github.com/stereolabs/zed-ros2-wrapper.git \
    && cd /opt/zed_ros2_ws \
    && . /opt/ros/${ROS_DISTRO}/setup.sh \
    && rosdep install --from-paths src --ignore-src -r -y \
    && colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc \
    && echo "source /opt/zed_ros2_ws/install/setup.bash" >> /etc/bash.bashrc

COPY tools /workspace/tools
COPY scripts /workspace/scripts
WORKDIR /workspace
CMD ["bash", "-lc", "source /opt/ros/${ROS_DISTRO}/setup.bash && source /opt/zed_ros2_ws/install/setup.bash && bash"]
